### ISSUE TITLE
Will compressed fastq.gz files be available as input in the future? 

### ISSUE THREAD

**Issue by StromTroopers** [steineggerlab/Metabuli#14]
Hello, thank you for this tool, it seems to be a very good alternative to kraken2 for example. 

I have a question about the input you need in Metabuli. At the moment, users can add fasta or fastq files.

I was wondering if in future releases you would consider adding the ability to add compressed fastq.gz files directly, as this would really save space for the various projects that aim to analyse a large number of raw reads.

All the best.

**Comment by JaebeomKim0731** [comment]
Thank you for reminding us of an important point.
Sure, we will add functionality to support compressed files.
Let me close this issue when we update the feature :) 
Thanks again!

**Comment by jaebeom-kim** [comment]
From Metabuli 1.0.2, `classify` and `add-to-library` support .gz files.
Thank you :)

**Comment by thanhleviet** [comment]
> From Metabuli 1.0.2, `classify` and `add-to-library` support .gz files. Thank you :)

@jaebeom-kim It's confusing when `(not compressed)` is still required in https://github.com/steineggerlab/Metabuli?tab=readme-ov-file#classification , I guess you might want to remove it from the README, thanks.

**Comment by jaebeom-kim** [comment]
@thanhleviet Thank you so much! I removed it.
