### ISSUE TITLE
metabuli-inspect?

### ISSUE THREAD

**Issue by sjaenick** [steineggerlab/Metabuli#18]
Hi again @JaebeomKim0731,

would it be possible (similar to `kraken2-inspect`) to provide a way to list the
taxa contained in a Metabuli database?

I'm currently playing around with assembled and binned metagenomic contigs
and different ways to taxonomically assign them; in cases where I obtain different
classifications from different approaches, it would be great to be able to check if
a certain taxon is included in a Metabuli database.

What do you think?

Sebastian

**Comment by jaebeom-kim** [comment]
Hi Sebastian,
That is a great idea. I agree with you.
I will provide it, soon.

**Comment by jaebeom-kim** [comment]
I added ```database-report``` workflow for it. Please see #21.
