### ISSUE TITLE
Memory unit consistency

### ISSUE THREAD

**Issue by sean-workman** [steineggerlab/Metabuli#19]
Hi there, 

This is a really small thing, but an easy fix. The help message and documentation here on GitHub show the unit for memory in GiB (which already led me to an out of memory error since I missed the i in G**i**B), but the log files show the RAM usage in GB. I suppose what the log says doesn't matter too much if the user knows they're using gibibytes, but I thought it worth pointing out anyway.

Cheers,
Sean

**Comment by jaebeom-kim** [comment]
Thanks for pointing it out! :) We missed it.
I'll take it into account in the next update.

**Comment by jaebeom-kim** [comment]
It is updated in the latest version. Thanks!
