### ISSUE TITLE
Low complexity regions in query reads.

### ISSUE THREAD

**Issue by jaebeom-kim** [steineggerlab/Metabuli#20]
Metabuli allocates memory for storing matches between query k-mers and reference k-mers.
When your FASTA or FASTQ files are populated with low-complexity sequences, the memory for matches is filled up so quickly.
In such cases, Metabuli generates ```overflow!!!``` signal in the log.
It doesn't kill the process, but the generated results files are expected to be unreliable.

Obviously, Metabuli should also be able to handle such cases, so we will improve this point soon.
Until we close this issue, if you meet ```overflow!!!``` signal in the log, please try again after filtering out low-complexity sequences.

**Comment by sjaenick** [comment]
Heng Li has a symmetric dustmasker implementation at https://github.com/lh3/minimap2/blob/master/sdust.c
that you might consider to include; there's also a multithreaded implementation at https://github.com/DerrickWood/kraken2/blob/master/src/k2mask.cc

**Comment by jaebeom-kim** [comment]
Thank you for the suggestion!
Metabuli already has a ```--mask``` option for ```build```, which masks low-complexity regions of reference sequences during DB creation using TANTAN.
But we didn't use the option for the pre-computed DBs, so such cases facing ```overflow!!!``` occurred. 
We will rebuild DBs using the option, which will reduce matches from low-complexity regions.
Query k-mers will still be extracted from the regions, but there will be much fewer matching reference k-mers.
  
```gtdb207+human.tar``` and ```refseq_virus``` are already updated.
We will update the other DBs and close this issue.

**Comment by sean-workman** [comment]
I filtered out the low complexity regions of my reads with bbduk.sh and the issue was fixed when using the GTDB database, but I'm seeing `overflow!!!` again when trying to use the full RefSeq217 database. I guess your above message explains it!

I eagerly await the updated RefSeq database. :)

**Comment by jaebeom-kim** [comment]
Hi, @sean-workman.
We updated the RefSeq database (refseq_complete_chromosome+human.tar), please try 😄

**Comment by sean-workman** [comment]
It is running now with a file that no longer has any low complexity regions - at least I didn't see any `overflow!!!` with the refseq_virus DB. One of my files did still have the `overflow!!!` though, but I don't think I can entropy trim any more without starting to lose lots of real reads.

This is excellent for now! Do you have any idea on a timeline for updating to ignore homopolymeric sequences? :)

**Comment by jaebeom-kim** [comment]
I added functionality to mask low-complexity regions of query reads. Please see #21 :)

+ The low-complexity masked RefSeq217 is in tar zipping. It will be uploaded soon :)

**Comment by sean-workman** [comment]
Hi Jaebeom,

I am trying to run with `--mask 1` and the program is crashing a lot...

I am analyzing the core dump files with `gdb` and this is what I see:

```
Reading symbols from metabuli...
[New LWP 173165]
[New LWP 173166]
[New LWP 173164]
[New LWP 173163]
[New LWP 172768]
[New LWP 173167]
[New LWP 173139]
[New LWP 173140]
[New LWP 173168]
[New LWP 173141]
[New LWP 173169]
[New LWP 173142]
[New LWP 173143]
[New LWP 173144]
[New LWP 173145]
[New LWP 173146]
[New LWP 173147]
[New LWP 173148]
[New LWP 173149]
[New LWP 173151]
[New LWP 173150]
[New LWP 173152]
[New LWP 173153]
[New LWP 173155]
[New LWP 173154]
[New LWP 173156]
[New LWP 173158]
[New LWP 173157]
[New LWP 173159]
[New LWP 173160]
[New LWP 173161]
[New LWP 173162]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/cvmfs/soft.computecanada.ca/gentoo/2020/lib64/libthread_db.so.1".
Core was generated by `metabuli classify /home/sdwork/scratch/metagenomics/och/adapter_trimmed/OCH12_t'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50        return ret;
[Current thread is 1 (Thread 0x2b90c9360700 (LWP 173165))]
```

and the `.err` file shows:

```
corrupted size vs. prev_size
/var/spool/slurmd/job7646081/slurm_script: line 17: 172768 Aborted                 (core dumped) metabuli classify $forward_read $reverse_read $DB $base_filename $base_filename --mask 1 --threads 32 --max-ram 128 --print-log 1
metabuli: malloc.c:4036: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
```

This is using the GTDB database. Looking at the log files it doesn't appear that there is any indication that the program would stop. The program just ends and goes on to the next set of input reads (I am running a bash loop to iterate through all of my samples one by one).

**Comment by jaebeom-kim** [comment]
Sorry. It was a silly bug. :sweat_smile:
I think now it works!

**Comment by sean-workman** [comment]
I re-built and am trying again!

I am trying with the GTDB, RefSeq Complete, RefSeq Virus, and RefSeq 217.

All of my batches of runs started with the same input files from my sample OCH12, and I am running all of batches with `--mask 1`. For some reason I am still seeing `overflow!!!` with the RefSeq 217 database, but not with any of the others. I just downloaded and extracted this database this morning, so it was after the new database was uploaded. I am trying again with `--match-per-kmer 8` - I will keep you posted!

**Comment by jaebeom-kim** [comment]
From Metabuli 1.0.4, `--match-per-kmer` is adjusted automatically when the situation of `overflow` occurs.
So, users don't have to consider this problem anymore :)
"--match-per-kmer was increased to X and searching again..." will be printed.
If it's printed too frequently, users can save auto-adjustment time by starting classification with a higher value for the parameter.
