### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by bcpd** [steineggerlab/Metabuli#30]
Hi -  I recently installed Metabuli (great tool -- thank you) with conda and got the "bus error" mentioned above following two attempts, one on illumina paired-end reads and the other on Nanopore reads. Have you seen this before (I have not)?
Thanks for your help.

**Comment by jaebeom-kim** [comment]
We didn't update the conda package after fixing some bugs which generated "core dumped" error. So, could you try to compile and use the latest source code?

**Comment by bcpd** [comment]
Thank you for the quick reply - that did the trick.
