### ISSUE TITLE
Add the full taxonomic classification to JobID_classifications.tsv

### ISSUE THREAD

**Issue by Serka-M** [steineggerlab/Metabuli#36]
Hello, thank you for developing Metabuli, it has worked great with my test datasets!

One minor suggestion is to add or have an option to add the full taxonomy in `JobID_classifications.tsv` or a similar report.

For example, if a read or contig gets classified down to species level, such as `Escherichia coli ` using GTDB  pre-built database, it would be great to have the full `d__Bacteria; p__Pseudomonadota; c__Gammaproteobacteria; o__Enterobacterales; f__Enterobacteriaceae; g__Escherichia; s__Escherichia coli` output automatically included in the report.

This feature would make metabulis output way more user-friendly and interpretable, especially for people who don't want to spend time sifting through taxID numbers.

Cheers!

**Comment by jaebeom-kim** [comment]
It is finally implemented!
You can set `--lineage 1` during `classify` to get full lineages printed in `JOBID_classifications.tsv` file.

**Comment by Serka-M** [comment]
Excellent, I've tested it out and it works great!
One minor thing to note is the prefixes are bit misformatted, but can easily be fixed with some little wrangling. Cheers!

<img width="1015" alt="Image" src="https://github.com/user-attachments/assets/c9e238a0-133d-4eeb-8ad9-ac5ebe5050b5" />
