### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by matsepp** [steineggerlab/Metabuli#42]
Hello,

I have built a custom database, and during the analysis step, I get:

```bash
(...)
Extracting query metamers ...
Time spent for metamer extraction: 52
Sorting query metamer list ...
Time spent for sorting query metamer list: 293
Comparing query and reference metamers...
Bus error (core dumped)
```

I wonder if my custom reference is to blame, or my reads, or something else, the db files look like this:

```bash
-rw-r--r-- 1 user group 3879768762 Nov 16 15:44 0_diffIdx
-rw-r--r-- 1 user group 3754395992 Nov 16 15:44 0_info
(...)
-rw-r--r-- 1 user group 3925091364 Nov 16 16:12 7_diffIdx
-rw-r--r-- 1 user group 3800137728 Nov 16 16:12 7_info
-rw-r--r-- 1 user group 3917471188 Nov 16 16:16 8_diffIdx
-rw-r--r-- 1 user group 3782011244 Nov 16 16:16 8_info
-rw-r--r-- 1 user group 3909695158 Nov 16 16:21 9_diffIdx
-rw-r--r-- 1 user group 3783195404 Nov 16 16:21 9_info
-rw-r--r-- 1 user group    1596492 Nov 16 15:40 acc2taxid.map
-rw-r--r-- 1 user group          0 Nov 16 21:03 diffIdx
-rw-r--r-- 1 user group          0 Nov 16 21:03 info
-rw-r--r-- 1 user group          0 Nov 16 21:03 split
-rw-r--r-- 1 user group   63045551 Nov 16 15:40 taxID_list
drwxr-xr-x 2 user group         98 Nov 16 15:26 taxonomy
```
There are these files of size 0, it this expected ?

Thanks for the help

Mathieu

**Comment by matsepp** [comment]
Note that I used https://mmseqs.com/metabuli/metabuli-linux-sse2.tar.gz downloaded this week

**Comment by matsepp** [comment]
about 30000 genomes. It seems to have peaked at 40GB ram. The server has 1TB, and the task was given 64 cores. I don't think ressources were the issue.
And run in a singularity container.

**Comment by jaebeom-kim** [comment]
I'm sorry for the delay in resolving the issue. 
We are currently occupied by other tasks, and I think I can look at the problem after mid of December.

Based on the printed message, I found that the error occurs in function `FileMerger::smallest()`. 
It seems related to taxonomy. Could you provided taxonomy dump files?

**Comment by jaebeom-kim** [comment]
Thank you. If you downloaded the ~30,000 genomes from public databases, could you provide the (assembly) accession? I will try to reproduce the error.

**Comment by matsepp** [comment]
Hi, when I was preparing the list of genomes I realised that I had actually concatenated them all into one fasta. That was the problem. It works now with 30,000 individual fasta.
