### ISSUE TITLE
Random Bus error during database building

### ISSUE THREAD

**Issue by ksandor79** [steineggerlab/Metabuli#43]
Dear authors,

Thank you for your work, I'm glad I found this program. Based on the runs I've done so far, I've gotten pretty reliable results with the pre-built databases. My problem is that I want to build a custom database that includes all archaeal, bacterial and fungal reference genomes (23.547 genomes in total). Unfortunately, despite my many attempts, I was unable to create the database, because after executing the build command, the runs stopped at completely random stages with a Bus error message (the total size of the generated files ranged from 5 to 220 GB). During the database building, I followed the description found on your site and used the provided scripts. I was able to complete these steps without any problems. After the build command was executed, I monitored my computer's resources and did not experience any storage or free memory issues. I tried to run the software on several computers running Ubuntu 23.10 and Microsoft WSL2 environment as well. In each case, I tried both the precompiled version and the version compiled by myself. Can you help me to solve this issue?

Thanks,
Sandor

**Comment by jaebeom-kim** [comment]
Thank you for reaching out.
Could you provide some printed logs of `build` process? 
It would be helpful to find the reason of the error.

**Comment by ksandor79** [comment]
Dear Jaebeom,

I started a build process to get a log. Is a simple dmesg log right for you?
By the way, for smaller datasets, the database was created without any problems. I also tried updateDB, but unfortunately it didn't work either, because it deleted the old database and created a new one only from the new fasta sequences.
 
Thanks,
Sandor

**Comment by jaebeom-kim** [comment]
Dear Sandor,

Thank you for your cooperation! 
I just need logs printed by `metabuli build`, but if you can provide further information, it would be thankful. 
About the `updateDB` module, it is still under development, and it is my fault to make the module visible to users.
Sorry for the confusion.

Sincerely,
Jaebeom

**Comment by ksandor79** [comment]
Dear Jaebeom,

No problem, the fact that you are working on such a feature is good in itself. I attach the logs. This time, the build process stopped with a Segmentation fault message. So far, I've only experienced this on Ubuntu and only when my monitor went to sleep and I woke it up by moving the mouse. Since I disabled this feature, I haven't received this error message. I know this is pretty weird, I don't understand it either. The current build process simply stopped with the error message, the other log file is perhaps more informative. I started this run in WSL2, but I will be launching a new build on Ubuntu shortly.

[metabuli_log_last_lines.txt](https://github.com/steineggerlab/Metabuli/files/13535954/metabuli_log_last_lines.txt)
[dmesg_last_lines.txt](https://github.com/steineggerlab/Metabuli/files/13535955/dmesg_last_lines.txt)

Thanks,
Sandor

**Comment by ksandor79** [comment]
Dear Jaebeom,

I managed to finish the build process yesterday. The difference from previous attempts was that I used the Docker image you made available. I managed to build the custom database on a machine that I had tried both the precompiled/compiled version without any success. I hope this observation helps you find the source of the problem.

Thanks,
Sandor

**Comment by jaebeom-kim** [comment]
Dear Sandor,

I'm happy to hear that your custom database is finally constructed.
But I still want to resolve the problem for other users or your later usage.

If you use the Docker image generated after the latest update on 2023-12-08, the problem may be solved due to changes in the update.
It is possible because we had fixed some errors in the database creation process.
I think we can check it by using Metabuli compiled from the latest source code.
Could you please try this if it doesn't bother you too much?

With thanks,
Jaebeom
