### ISSUE TITLE
add-to-library for custom db - std::logic_error

### ISSUE THREAD

**Issue by lerminin** [steineggerlab/Metabuli#52]
Hello, 

I am trying to build a custom db for 98 NCBI RefSeq fungal genomes and am running into the following error. I'm not sure if this is a bug or if there is something wrong with the structure of my input files:

command (metabuli v1.0.1):
`metabuli add-to-library fasta_list.txt  accession2taxid  metabuli_refseq_fungi_db`  

output:
```
Loading nodes file ... Done, got 2550799 nodes
Loading merged file ... Done, added 75762 merged nodes.
Loading names file ... Done
Init RMQ ...Done
Load mapping from accession ID to taxonomy ID
done
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
```

head accession2taxid:
```
accession	accession.version	taxid	species_taxid
GCF_000002945	GCF_000002945.1	4896	4896
GCF_003054445	GCF_003054445.1	4909	4909
GCF_000243375	GCF_000243375.1	4950	4950
GCF_000026365	GCF_000026365.1	4956	4956
```

head fasta_list.txt:
```
/path/metabuli_refseq_fungi_db/library/GCF_000219625.1_MYCGR_v2.0_genomic.fna.gz
/path/metabuli_refseq_fungi_db/library/GCF_014133895.1_ASM1413389v1_genomic.fna.gz
/path/metabuli_refseq_fungi_db/library/GCF_019915245.1_ASM1991524v1_genomic.fna.gz
/path/metabuli_refseq_fungi_db/library/GCF_000027005.1_ASM2700v1_genomic.fna.gz
```

In my DBDIR (metabuli_refseq_fungi_db) I have a `taxonomy` folder containing the unpacked files from [NCBI taxdump](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/), and a `library` folder containing the gzipped fasta sequences. The documentation on the README and on the `--help` page for `add-to-library` are not clear to me whether the fasta files should already be stored in `DBDIR/library` before running `add-to-library` or if they can be stored elsewhere, but I have tried both and am getting the same error. 

Appreciate any help you can provide, thanks!

**Comment by jaebeom-kim** [comment]
Thank you for reaching out!

_The documentation on the README and on the --help page for add-to-library are not clear to me whether the fasta files should already be stored in DBDIR/library before running add-to-library or if they can be stored elsewhere, but I have tried both and am getting the same error._

The fasta files shouldn't be stored in DBDIR/library.

I want to check your `accession2taxid` file.
Metabuli uses it to map each sequence in a FASTA file to a corresponding taxonomy ID.
Here, accessions are identifiers next to `>` in headers of sequences.
For example,
if one of your sequence looks like below,
```
>example1.1 someothertext
AAAATTTTAAAATTTTAACCCGGG
```
`example1.1` should be in the `accession2taxid` file.

I want to know if your FASTA files and `accession2taxid` file are formatted like this.

Thank you!
Jaebeom

**Comment by jaebeom-kim** [comment]
I want to ask you to try this quick fix.

1. From your `accession2taxid` file, make a tsv file looks like below
```
GCF_000002945.1	4896
GCF_003054445.1	4909
GCF_000243375.1	4950
GCF_000026365.1	4956
```
Note that It doesn't have a header line.

2. Give the new tsv file and add `--assembly true`.
```
metabuli add-to-library fasta_list.txt  NEW_TSV_FILE  metabuli_refseq_fungi_db --assembly true
```
With `--assembly true` option, Metabuli will map _each FASTA file_ to a taxon.
(In contrast to mapping _each sequence_ without the option)
Metabuli will extract assembly accessions (`GCF_000002945.1`) from paths in `fasta_list.txt`.
For example, `GCF_000219625.1` will be extracted from `/path/metabuli_refseq_fungi_db/library/GCF_000219625.1_MYCGR_v2.0_genomic.fna.gz` 
Then, the accession is used to map the FASTA.

**Comment by lerminin** [comment]
Thanks for the assistance!

I modified my `accession2taxid` file to the following using a subset of 3 assemblies:
```
GCF_027921745.1	2545709
GCF_013368755.1	121627
GCF_025433545.1	1328300
```
I ran the following:
`metabuli add-to-library fasta_list.txt  NEW_TSV_FILE  metabuli_refseq_fungi_db --assembly true`

but am getting the same `std::logic` error as above. 

I tried with ungzipped fasta files and re-ran the same `add-to-library` command which appears to have executed without errors:
```
Loading nodes file ... Done, got 2550799 nodes
Loading merged file ... Done, added 75762 merged nodes.
Loading names file ... Done
Init RMQ ...Done
Load mapping from assembly accession to taxonomy ID
Write mapping from accession to taxonomy ID
Time for processing: 0h 0m 4s 817ms
```
which generated `my.accession2taxid` file in the DBDIR that has a new line for each fasta record within each assembly:
```
accession	accession.version	taxid	gi
NW_026515666	NW_026515666.1	1328300	0
NW_026515664	NW_026515664.1	1328300	0
NC_070532	NC_070532.1	1328300	0
NW_026515663	NW_026515663.1	1328300	0
NC_070531	NC_070531.1	1328300	0
```
but the DBDIR/library folder remains empty, which I assume causes a problem for the `build` step? should the DBDIR/library contain the fasta sequences after running `add-to-library`?

**Comment by lerminin** [comment]
I upgraded to v1.0.2, and along with the `--assembly true` and re-formatting the `accession2taxid` file, I was able to successfully build the database. 

Thanks again for the assistance!
