### ISSUE TITLE
Can't download the database in China

### ISSUE THREAD

**Issue by houjialin** [steineggerlab/Metabuli#67]
Hi, thank you for developing this amazing tool ! I'm very interested to try it in our new metagenomic project, however, here is the problem for me : I can't access the link address of the database [gtdb.tar.gz (https://metabuli.steineggerlab.workers.dev/gtdb.tar.gz) in China, so could you help me provide another link that more easier for me to download the database, e.g. google drive or Zenodo or others ? 
Thank you very much~

**Comment by jaebeom-kim** [comment]
Thank you for reaching out!
I'm working on making a Zenodo page for GTDB database.
I'll let you know when it is ready!
Thank you :)

**Comment by jaebeom-kim** [comment]
It's ready now!
Thank you for waiting!
Since Zenodo allows 50 GB for each page, the GTDB uploaded into two parts.
PART 1: https://zenodo.org/records/12207057
PART 2: https://zenodo.org/records/12207189
Please download all the files and perform `gzip -d` for `info.gz` and `diffIdx.gz` files.

**Comment by Maiya19724** [comment]
@jaebeom-kim many thanks, my friends. that helps me a lot

**Comment by houjialin** [comment]
@jaebeom-kim Thank you so much !
