### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Maiya19724** [steineggerlab/Metabuli#71]
Thank you for providing such an excellent tool. I have some questions regarding its performance. 

My dataset contains 1,005,878 sequences with a total length of 11,798,865,237. I am using the GTDB-r214 database. Despite utilizing all available threads and limiting the RAM to 200GB, the processing speed seems quite slow. I have noticed that the CPU usage remains relatively low for most of the runtime. 
(It seems that the CPU is fully used only during the "Analyzing matches..." phase. ) 

Are there any methods to improve the processing speed?

**Comment by jaebeom-kim** [comment]
Sorry for the delayed answer.
It seems like your data is a long-read sample, and Metabuli takes more time in "Analyzing matches..." phase for long-read data.
How many threads are you using? 
I observed that increasing the number of threads decreased the CPU usage during process touching the hard disk.
It would be very helpful if you can provide the printed log (the message printed with "Analyzing matches...").
I also want to know if the task was completed at the end.
Thanks a lot!

**Comment by jaebeom-kim** [comment]
Thank you for detailed explanations.
The latest release solved an issue related to `--max-ram` setting, I hope this fixation also would solve your problem.
Please try it when you afford :)

Best regards!

**Comment by Maiya19724** [comment]
I will give it a try. Thank you for your hard work!
