### ISSUE TITLE
Specify multiple fastqs

### ISSUE THREAD

**Issue by kazumaxneo** [steineggerlab/Metabuli#81]
Hi,

In "metabuli classify" commnad,  is it possible to specify multiple fastqs  ? (e.g. as a list)
I would like to reduce the D.B loading time for profiling thousands of SRA fastqs.

Best, 

Kazuma

**Comment by jaebeom-kim** [comment]
Hi Kazuma!
Currently, Metabuli doesn't support processing multiple samples.

But... Metabuli doesn't load DB on the RAM, so you can run it multiple times without worrying the DB loading time!

Thanks a lot!

Jaebeom

**Comment by kazumaxneo** [comment]
Dear Jaebeom

Great !
I'll try now with pre-build GTDB R214 DB.
Thank you for your quick reply.
I will be sure to cite Metabuli in the coming paper.

Best,
