### ISSUE TITLE
Taxonkit support release 

### ISSUE THREAD

**Issue by esteinig** [steineggerlab/Metabuli#99]
Hey @jaebeom-kim,

really enjoying Metabuli, fantastic work!

I am routinely building grafted / adjusted taxonomies with `taxonkit` and was wondering if the changes in the fork below could be pulled into the next release / Bioconda release, so we can test using Metabuli in production?

FYI the fix works for other `taxonkit` adjusted taxonomies like the NCBI/GTDB grafts outlined in the Tutorials.

> Currently, I am using this version of Metabuli: Metabuli Version 1.0.8. I have a question: is the version I downloaded different from the one available in this directory? -> https://github.com/jaebeom-kim/Metabuli

Yes, please use `https://github.com/jaebeom-kim/Metabuli` when you try the ICTV database. Sorry for this inconvenience. Taxonkit uses the full range of 32 bit integer for taxonomy ID, but Metabuli used only 31 bits, so I made a quick fix in my fork.

>Another question: Should I download the nodes.dmp and names.dmp files from here > https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/ or do I need to build my own taxonomy files using TaxonKit and create an ICTV taxdump file?

You don't need to download any dmp files to try the ICTV database.
But, I just shared dmp files in https://hulk.mmseqs.com/jaebeom/vmr39.2/ictv-taxdump/ just in case.

Thanks again!

_Originally posted by @jaebeom-kim in https://github.com/steineggerlab/Metabuli/issues/96#issuecomment-2428319633_

**Comment by jaebeom-kim** [comment]
Thank you for waiting for Taxonkit support!
I just made a PR including the support.
Hope it works well for you.

**Comment by esteinig** [comment]
Wonderful, thank you so much for this :)

**Comment by jaebeom-kim** [comment]
The PR is merged now. Thank you for providing a great opinion!
